import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';
import { VitePWA } from 'vite-plugin-pwa';

export default defineConfig({
  plugins: [
    sveltekit(),
    VitePWA({
      // adapter-static already writes a fully static site to build/ —
      // SvelteKitPWA just needs to inject the manifest + service worker
      // registration into it.
      strategies: 'generateSW',
      registerType: 'autoUpdate',
      injectRegister: false,
      includeAssets: ['favicon.svg', 'favicon.png'],
      manifest: {
        name: 'Floorish',
        short_name: 'Floorish',
        description: "Floorish — Draw your home's floor plan and preview it in 3D. Free and open source.",
        theme_color: '#1E3D1E',
        background_color: '#FAF8F4',
        display: 'standalone',
        start_url: '/',
        scope: '/',
        icons: [
          {
            src: 'icons/icon-192.png',
            sizes: '192x192',
            type: 'image/png'
          },
          {
            src: 'icons/icon-512.png',
            sizes: '512x512',
            type: 'image/png'
          },
          {
            src: 'icons/icon-512-maskable.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable'
          }
        ]
      },
      workbox: {
        // Everything here is generated by npm run build (adapter-static),
        // so precache it all for full offline support.
        globPatterns: ['**/*.{js,css,html,svg,png,webmanifest}'],
        navigateFallback: '/index.html'
      },
      devOptions: {
        // Service worker is disabled in `vite dev` — it only matters for
        // the built/deployed app, and enabling it in dev causes stale
        // caching of the module graph while iterating.
        enabled: false
      }
    })
  ]
});
